### ISSUE TITLE
ArgumentException: Requested value 'leftup' was not found.

### ISSUE THREAD

**Issue by danielscherzer** [Ragath/TiledLib.Net#2]
Hi,

thanks for creating your extension.

I get the following exception, in the line`var map = Map.FromStream(stream, ts => File.OpenRead(Path.Combine(Path.GetDirectoryName(fileName), ts.source)));`
```
System.InvalidOperationException
  HResult=0x80131509
  Message=There is an error in XML document (2, 2).
  Source=System.Private.Xml
  StackTrace:
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at TiledLib.Utils.ReadTmxMap(TextReader reader)
   at TiledLib.Map.FromStream(Stream stream, Func`2 tsLoader)
...
Inner Exception 1:
ArgumentException: Requested value 'leftup' was not found.
```
with map: [grass.zip](https://github.com/Ragath/TiledLib.Net/files/2400617/grass.zip)

in an .net core 2.0 console application.
Used Tiled 2018.5.24 and MSVS Enterprise 15.8.4

**Comment by Ragath** [comment]
thanks for the feedback, this problem should be resolved in the next release(going public in a couple of minutes hopefully).

**Comment by danielscherzer** [comment]
Thanks for the quick fix. Regrettably after the update another inner exception is thrown:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=There is an error in XML document (50, 5).
  Source=System.Private.Xml
  StackTrace:
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at TiledLib.Utils.ReadTmxMap(TextReader reader)
   at TiledLib.Map.FromStream(Stream stream, Func`2 tsLoader)

Inner Exception 1:
InvalidOperationException: There is an error in XML document (50, 5).

Inner Exception 2:
XmlException: point at TiledLib.TmxLayers.ReadObject(XmlReader reader)    at 
TiledLib.Layer.ObjectLayer.ReadXml(XmlReader reader)    at 
System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)    at 
Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderObjectLayer.Read1_objectgroup()    --- End of inner exception stack trace ---    at 
System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)    at TiledLib.TmxMap.ReadMapElements(XmlReader reader, Map map)    at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)    at 
Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMap.Read1_map()} | System.Exception {System.InvalidOperationException}
```

**Comment by Ragath** [comment]
Should be fixed in the latest release

**Comment by danielscherzer** [comment]
Excellent work! Thank you
